name: test_integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run test_talbot.sh file
      run: |
         chmod +x ./talbot/test_talbot.sh
         ./talbot/test_talbot.sh
      shell: bash
