name: "Run YAML Configuration Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run YAML config integration test
      run: bash integration_tests/yaml_test.sh

